### PR TITLE
Update emscripten to 3.1.3

### PR DESCRIPTION
**Pull request by tmm1**
continuation of #12 

3.1.4 onwards fails as discussed in https://github.com/StarGate01/Full-Stack-Fortran/issues/10#issuecomment-1121623837

### CODE REVIEW

**Comment by StarGate01** [comment]
Thanks for the PR, unfortunately compilation of the test programs fails: 

```
wasm-ld: error: /project/bin/.emscripten_cache/sysroot/lib/wasm32-emscripten/lto/libnoexit.a(atexit_dummy.o): attempt to add bitcode file after LTO.
emcc: error: '/app/emsdk/upstream/bin/wasm-ld -o bin/assembly.wasm bin/assembly.bc -L/project/bin/.emscripten_cache/sysroot/lib/wasm32-emscripten/lto -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=__test_MOD_add --export-if-defined=__test_MOD_dotest --export-if-defined=__lapack_prb_MOD_lapack_prb_main --export-if-defined=__test_eigen_MOD_test_eigen_main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=malloc --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (returned 1)
make: *** [bin/assembly.js] Error 1
makefile:99: recipe for target 'bin/assembly.js' failed
```

Did you clear your cache? (Delete `test/bin`, especially `test/bin/.emscripten_cache`)

**Comment by tmm1** [comment]
Bummer. I was only testing with my own simpler fortran code. I'll try `test.sh` to see what happens.

**Comment by StarGate01** [comment]
This might not necessarily be a problem with the LLVM compatibility if it works for your example then, instead the tooling usage could have changed. This would mean that the makefile for the test program has to be adjusted to invoke the new Emscripten tools the proper way. One such deprecation example is mentioned by the compiler even: "emcc: warning: bitcode linking with llvm-link is deprecated.  Please use emar archives instead.  See https://github.com/emscripten-core/emscripten/issues/13492 [-Wdeprecated]" .

**Comment by tmm1** [comment]
Okay I see all the same warnings and the error at the end with the test as well.

None of that is happening with a pure-fortran code build, FWIW.

**Comment by StarGate01** [comment]
I suspect the issue comes from how the individual objects files (`.bc`) are linked and archived together. How do you link your simple test program? Does it consist of multiple object files?

**Comment by tmm1** [comment]
> attempt to add bitcode file after LTO

Similar thread here? https://github.com/emscripten-core/emscripten/issues/16836

**Comment by tmm1** [comment]
> How do you link your simple test program? Does it consist of multiple object files?

It's just one huge fortran file.

https://github.com/tmm1/taxsim.js/blob/main/Dockerfile#L3-L12

**Comment by StarGate01** [comment]
Hm. since libgfortran.a consists of several bytecode files compiled from both C as well as Fortran, linking with archives seems to be working. There seems to be an issue with either the example makefile, or some kind of LTO incompatibility.

**Comment by tmm1** [comment]
> Similar thread here? [emscripten-core/emscripten#16836](https://github.com/emscripten-core/emscripten/issues/16836)

Must be, because I got things to compile as follows:

```diff
-EMSFLAGS:=$(OPT) $(DEBUG) -m32 -Wall -flto
+EMSFLAGS:=$(OPT) $(DEBUG) -m32 -Wall -flto -Wl,-u,atexit -Wl,-u,__cxa_atexit
```

There is a lot of output in the dev console, so I think its working fine?

**Comment by tmm1** [comment]
Except I also see this now, so I'm not sure how exactly the compile started working..

```
emcc -O3  -m32 -Wall -flto -Wl,-u,atexit -Wl,-u,__cxa_atexit -r -o bin/assembly.bc bin/iolib/iolib.c.bc bin/iolib/iolib.f90.bc bin/test.f90.bc bin/lapack_test/test_eigen.f90.bc bin/lapack_test/lapack_prb.f90.bc /app/lib/libgfortran.a /app/lib/liblapack.a /app/lib/librefblas.a
emcc: warning: ignoring unsupported linker flag: `-u` [-Wlinkflags]
emcc: warning: ignoring unsupported linker flag: `atexit` [-Wlinkflags]
emcc: warning: ignoring unsupported linker flag: `-u` [-Wlinkflags]
emcc: warning: ignoring unsupported linker flag: `__cxa_atexit` [-Wlinkflags]

**Comment by StarGate01** [comment]
Your fix works, good call! I'll file that as an oversight by the Emscripten devs, similar to `fputc` in the issue you mentioned.

This leaves us with the same warnings as in #12 , but at least the tests now properly compile and run.

Concering the `ignoring unsupported linker flag`; the EMSFLAGS flags are used in two makefile stages, maybe one is ignoring the flags? In addition, emcc is essentially just a wrapper around LLVM/clang. As long as the LLVM linker somehow receives the linker flags, it does not matter whether emcc actually understands the flags. Since it works now, it must have done _something_ .

**Comment by tmm1** [comment]
Yea you were right. I cleaned it up and moved the compiler and linker flags to the correct commands.

**Comment by tmm1** [comment]
If you search for "is not valid according to llvm-nm" it seems like that message it not uncommon during emscripten builds? Not sure..

**Comment by tmm1** [comment]
> emcc: warning: generating an executable with an object extension (.bc).  If you meant to build an object file please use `-c, `-r`, or `-shared` [-Wemcc]

This warning seems to be due to a bug: https://github.com/emscripten-core/emscripten/issues/15760

**Comment by StarGate01** [comment]
The warning seems to be generated at https://github.com/emscripten-core/emscripten/blob/3.1.3/tools/building.py#L423= , which checks the result of https://github.com/emscripten-core/emscripten/blob/3.1.3/tools/building.py#L198=  - maybe `parse_error` is set mistakenly? Alternatively, llvm-nm might actually fail to parse the objects due to some version incompatibility.

**Comment by tmm1** [comment]
> emcc: warning: bitcode linking with llvm-link is deprecated.  Please use emar archives instead.  See https://github.com/emscripten-core/emscripten/issues/13492 [-Wdeprecated]

This one was added in https://github.com/emscripten-core/emscripten/pull/15724 and is mentioned on https://github.com/emscripten-core/emscripten/issues/15760#issuecomment-995979503

**Comment by StarGate01** [comment]
I am not too worried about deprecation warnings just yet, as long as the functionality still exists. Still, packing the object files into an archive and then linking the against that archive would be a lot cleaner in any case.

**Comment by tmm1** [comment]
>emcc: warning: object /tmp/emscripten_temp_rzc7e3xl_archive_contents/_sinh_r10.F90.bc is not valid according to llvm-nm, cannot link [-Wemcc]

```
$ /app/emsdk/upstream/bin/llvm-nm /tmp/emscripten_temp_rzc7e3xl_archive_contents/_sinh_r10.F90.bc; echo $?

/tmp/emscripten_temp_rzc7e3xl_archive_contents/_sinh_r10.F90.bc: no symbols
0
```

**Comment by tmm1** [comment]
>emcc: warning: object /tmp/emscripten_temp_rzc7e3xl_archive_contents/la_constants.o is not valid according to llvm-nm, cannot link [-Wemcc]

```
$ ls -alh /tmp/emscripten_temp_rzc7e3xl_archive_contents/la_constants.o
-rw-r--r-- 1 root root 460 Jan  1  1970 /tmp/emscripten_temp_rzc7e3xl_archive_contents/la_constants.o

$ /app/emsdk/upstream/bin/llvm-nm /tmp/emscripten_temp_rzc7e3xl_archive_contents/la_constants.o
/tmp/emscripten_temp_rzc7e3xl_archive_contents/la_constants.o: no symbols
```

here's another that has more data:

>emcc: warning: object /tmp/emscripten_temp_rzc7e3xl_archive_contents/maxloc0_16_r16.c.bc is not valid according to llvm-nm, cannot link [-Wemcc]

```
$ ls -alh /tmp/emscripten_temp_rzc7e3xl_archive_contents/maxloc0_16_r16.c.bc
-rw-r--r-- 1 root root 1.7K Jan  1  1970 /tmp/emscripten_temp_rzc7e3xl_archive_contents/maxloc0_16_r16.c.bc

$ /app/emsdk/upstream/bin/llvm-nm /tmp/emscripten_temp_rzc7e3xl_archive_contents/maxloc0_16_r16.c.bc
/tmp/emscripten_temp_rzc7e3xl_archive_contents/maxloc0_16_r16.c.bc: no symbols

$ llvm-nm-3.3 /tmp/emscripten_temp_rzc7e3xl_archive_contents/maxloc0_16_r16.c.bc
llvm-nm-3.3: /tmp/emscripten_temp_rzc7e3xl_archive_contents/maxloc0_16_r16.c.bc: Unknown bitstream version!.
```

**Comment by StarGate01** [comment]
Yea, I noticed that `/app/emsdk/upstream/bin/llvm-nm --print-file-name /app/lib/libgfortran.a` emits e.g. `/app/lib/libgfortran.a:time.c.bc: no symbols` for all entries that generate a "is not valid according to llvm-nm, cannot link [-Wemcc]" error. 

Makes sense, symbols are required for linking. On the positive side, most objects in the archive contain symbols - the important ones like the `gfortran_*` library functions exists and are linked properly.

So the question remains, why are some object files missing their symbols? And does it actually matter? Linking does not fail, even with `ERROR_ON_UNDEFINED_SYMBOLS=1`, so I suppose those symbols are not needed anyway?


> Unknown bitstream version! 

Hm. that's concerning. Maybe a LLVM incompatibility?

**Comment by tmm1** [comment]
> Hm. that's concerning. Maybe a LLVM incompatibility?

That's expected I think, since I'm using the really old llvm 3.3 to read emcc generated bc.

Mostly trying to show that real errors would be louder than whatever this no symbols thing is. Seems like its linking just fine, maybe nm just doesn't recognize bc files to be able to parse symbols out?

I guess we could verify if the older emscripten llvm-nm behaved any differently.

**Comment by StarGate01** [comment]
> I guess we could verify if the older emscripten llvm-nm behaved any differently.

Parsing some of the offending objects using both the LLVM bundled with emscripten, as well as llvm-3.3 used for emfc reveals:

```
root@879fca4a68ce:/app/test/bin/intrinsics# llvm-nm-3.3 --print-file-name time.c.bc 
llvm-nm-3.3: time.c.bc: Unknown bitstream version!.
root@879fca4a68ce:/app/test/bin/intrinsics# /app/emsdk/upstream/bin/llvm-nm --print-file-name time.c.bc 
time.c.bc: no symbols
[...]
root@879fca4a68ce:/app/test/bin/generated# /app/emsdk/upstream/bin/llvm-nm --print-file-name _acos_r16.F90.bc
_acos_r16.F90.bc: no symbols
root@879fca4a68ce:/app/test/bin/generated# llvm-nm-3.3 --print-file-name _acos_r16.F90.bc
[ no output ]
```
This is strange, since these object files are compiled using either LLVM 3.3 or the up-to-date Emscripten C compiler. But it confirms that these objects indeed have no symbols exported.

These warnings might stem from the way libgfortran is compiled. Maybe there are some "empty" objects with invalid / unsed / inlined functions.

**Comment by tmm1** [comment]
Here's time.c: https://github.com/gcc-mirror/gcc/blob/master/libgfortran/intrinsics/time.c

It defines two functions.. pretty simple.

Inside libfortran.a, the time.c.bc file is 1.7KB:

```
$ ls -alh time.c.bc
-rw-r--r-- 1 root root 1.7K May 10 00:08 time.c.bc
```

So clearly there is stuff in there. Some other files are only a 400 bytes or so.

My conclusion is that the symbols are in there, but in some format that llvm-nm doesn't understand.

Clearly both the test program and my code are working as expected, so I conclude these warnings are harmless noise.

**Comment by tmm1** [comment]
`llvm-dis` would show the contents of these .bc files, but emsdk doesn't bundle it..

EDIT: this worked:

```
$ llvm-bcanalyzer-3.3 time.c.bc
Summary of time.c.bc:
         Total size: 13792b/1724.00B/431W
        Stream type: LLVM IR
  # Toplevel Blocks: 4
...
```

**Comment by StarGate01** [comment]
I suspect the actual function code is never compiled, because is is guarded by macro checks such as `#if defined (HAVE_GFC_REAL_10)`. The `kinds.h` libgfortran file I included only defines real types of 4 and 8 bytes length, since I think wider types clash with the wasm types. However, the libgfortran makefile just compiles any intrisics for any datatypes, leading to a lot of empty objects. If you look at the objects file names, most of them concern datatypes that are not defined (eg. 10 or 16 byte wide types). I suspect the same kind of guards block files like time.c .

So yea, these errors can be probably ignored. I'll look into what types can actually be compiled, and the libgfortran makefile has to be adjusted to only include the filed needed.

**Pull request merged**
